---
title: "R Notebook"
output: html_notebook
#This script takes the output from Centrimo (a .tsv file) and plots as a grid. 
#I use Centrimo to look for core promoter elements within the region -1000 to +100 
#relative to the Transcription Start Site (TSS) using repressed gene list as background
#for activated genes.
---

#libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(tidyquant)

normalize <- function(motif){
  #this function adjusts the distance from centered to asymmetric, then 
  #normalizes within the two gene lists
  motif$bin_position <- as.numeric(motif$bin_position) - 450
  motif$activated <- as.numeric(motif$activated)/sum(as.numeric(motif$activated))
  motif$repressed <- as.numeric(motif$repressed)/sum(as.numeric(motif$repressed))
  return(motif)
}

normalize_multi <- function(motif){
  #same as above but used when running this script for multiple directories at once
  motif$bin_position <- as.numeric(motif$bin_position) - 450
  motif$genelist <- as.numeric(motif$genelist)/sum(as.numeric(motif$genelist))
  motif$background <- as.numeric(motif$background)/sum(as.numeric(motif$background))
  return(motif)
}
```

#Example: WT act genes norm to WT repressed genes
```{r message=FALSE, warning=FALSE}
# Command used:
# centrimo --oc wt_act_overrep --local --ethresh 10 --neg /home/tom/Documents/motif/all_WTrep_motif.fa /home/tom/Documents/motif/all_WTact_motif.fa /home/tom/anaconda3/envs/memesuite2/bin/20210304_JASPAR2018_combined_matrices_18942_meme.meme
# output folder was moved to a different directory before analysis

jaspar <- read_delim("/home/tom/anaconda3/envs/memesuite2/20210520_motif_finding/wt_act_overrep/site_counts.txt", "\t", col_names=c("bin_position", "activated", "repressed"))
pvals <- read_delim("/home/tom/anaconda3/envs/memesuite2/20210520_motif_finding/wt_act_overrep/centrimo.tsv", "\t", col_names=TRUE) %>% select(3,20) %>% na.omit()

#get names of motifs and pair with Fisher adjusted p-vals
jaspar %<>% mutate(motif = str_detect(jaspar$bin_position, "DB"))
motifs <- which(jaspar$motif==TRUE) %>% append(nrow(jaspar)+1)
sample_names <- jaspar$repressed[motifs]
sample_names %<>% na.omit()
sn <- sample_names %>% as_data_frame()
pvals <- pvals[order(match(pvals$motif_alt_id, sn$value)),]
colnames(pvals) <- c("motif","pval")

#create labels for plotting
labels <- data.frame(xval = rep(-240, length(sample_names))) %>% mutate(yval = rep(0.016, length(sample_names))) %>% cbind(pvals)

#initialize dataframe to accept transformed data
df <- data.frame()
for(i in (1:(length(sample_names)))){
  temp_df <- jaspar %>% 
    select(1:3) %>% 
    slice((motifs[i] + 1):(motifs[i + 1]-1)) %>% 
    normalize() %>%
    add_column(motif = sample_names[i]) %>%
    add_column(pval = pvals$pval[i])
  
  df %<>% rbind(temp_df)
}

#pivot df for plotting
df_long <- pivot_longer(df, c(2,3), names_to = "condition", values_to = "probability")

ggplot(df_long)+
    geom_vline(xintercept=0,alpha=.5,linetype="dashed")+
    geom_ma(aes(x=bin_position, y=probability, color=motif, linetype = condition), ma_fun=WMA, n=20, show.legend=TRUE)+
    scale_x_continuous(expand = c(0, 0), breaks = c(-250,0,100))+
    scale_y_continuous(expand = c(0, 0))+
    coord_cartesian(xlim=c(-250,100), ylim=c(0,NA))+
    labs(x = "distance from TSS")+
    theme_classic()+
    theme(text = element_text(size = 8, family = "Helvetica"),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.spacing.x = unit(2, "lines"),
      panel.border = element_rect(colour="black", fill = NA),
      strip.background = element_blank(),
      strip.text.y = element_text(margin = margin(b=-1,t=0)),
      axis.text.x = element_text(color="black"),
      axis.text.y = element_text(color="black"))+
    facet_wrap(~ motif, ncol = (length(sample_names)-1) %>% sqrt() %>% ceiling())+
    geom_text(data = labels, aes(x = xval, y = yval, label = paste0("p = ", pval)), inherit.aes = FALSE, size=3, hjust=0)
```

#multiplex
```{r message=FALSE, warning=FALSE}
# Centrimo does not change the file names, just the directory names
# so analyzing across many directories is very easy

dirs <- list.dirs("/home/tom/anaconda3/envs/memesuite2/bin", recursive = FALSE)
folders <- list.dirs("/home/tom/anaconda3/envs/memesuite2/bin", recursive=FALSE, full.names = FALSE)

j=1
for(j in 1:length(dirs)){
  jaspar <- read_delim(paste(dirs[j], "site_counts.txt", sep="/"), "\t", col_names=c("bin_position", "genelist", "background"))
  pvals <- read_delim(paste(dirs[j], "centrimo.tsv", sep="/"), "\t", col_names=TRUE) %>% select(3,20) %>% na.omit()

  jaspar %<>% mutate(motif = str_detect(jaspar$bin_position, "DB"))
  motifs <- which(jaspar$motif==TRUE) %>% append(nrow(jaspar)+1)
  sample_names <- jaspar$background[motifs]
  sample_names %<>% na.omit()
  sn <- sample_names %>% as_data_frame()
  pvals <- pvals[order(match(pvals$motif_alt_id, sn$value)),]
  colnames(pvals) <- c("motif","pval")
  labels <- data.frame(xval = rep(-240, length(sample_names))) %>% mutate(yval = rep(0.015, length(sample_names))) %>% cbind(pvals)

  df <- data.frame()
  for(i in 1:length(sample_names)){
    temp_df <- jaspar %>% 
      select(1:3) %>% 
      slice((motifs[i] + 1):(motifs[i + 1]-1)) %>% 
      normalize_multi() %>%
      add_column(motif = sample_names[i]) %>%
      add_column(pval = pvals$pval[i])
    df %<>% rbind(temp_df)
  }

  df_long <- pivot_longer(df, c(2,3), names_to = "condition", values_to = "probability")
  output <- paste("/home/tom/Documents/motif", folders[j], sep = "/") %>% paste0(".png")
  df_long$condition %<>% factor(levels = c("genelist", "background"))

  ggplot(df_long)+
    geom_vline(xintercept=0,alpha=.5,linetype="dashed")+
    geom_ma(aes(x=bin_position, y=probability, color=motif, linetype = condition), ma_fun=WMA, n=20, show.legend=TRUE)+
    scale_x_continuous(expand = c(0, 0), breaks = c(-250,0,100))+
    scale_y_continuous(expand = c(0, 0))+
    coord_cartesian(xlim=c(-250,100), ylim=c(0,0.016))+
    labs(x = "distance from TSS")+
    ggtitle(folders[j])+
    theme_classic()+
    theme(text = element_text(size = 8, family = "Helvetica"),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.spacing.y = unit(.3, "lines"),
      panel.spacing.x = unit(2, "lines"),
      panel.border = element_rect(colour="black", fill = NA),
      strip.background = element_blank(),
      strip.text.y = element_text(margin = margin(b=-1,t=0)),
      axis.text.x = element_text(color="black"),
      axis.text.y = element_text(color="black"))+
    facet_wrap(~ motif, ncol = (length(sample_names)-1) %>% sqrt() %>% ceiling())+ #scale = "free_y"
    geom_text(data = labels, aes(x = xval, y = yval, label = paste0("p = ", pval)), inherit.aes = FALSE, size=3, hjust=0) 
  
  #ggsave(output)
}
```

